apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- sa.yaml
- roles.yaml
- service.yaml
- deployment.yaml
replicas:
- count: 1
  name: cloud-event-consumer-deployment
images:
- name: cloud-event-consumer
  newName: quay.io/redhat-cne/cloud-event-consumer
  newTag: release-4.12
- name: cloud-event-sidecar
  newName: quay.io/redhat-cne/cloud-event-proxy
  newTag: release-4.12
